### ISSUE TITLE
*** stack smashing detected ***: /readhook/app/fullhook terminated

### ISSUE THREAD

**Issue by macedemo** [polyverse/readhook#1] opened 2018-03-06 13:01 UTC
I'm a little confused. I got this working ok on an Alpine container as you had it before but now you switch to centos which is good as was looking to do that myself and I got "*** stack smashing detected ***: /readhook/app/fullhook terminated" when I ran test.sh

looking at the dockerfile it sort of makes sense but not sure why you want stack smashing protection on. Thought you would want it off. 

i.e. see gcc -std=gnu99 -fstack-protector-all for all compiles

**Comment by rsundahl** [comment] 2018-03-06 21:58
Thank you for the feedback. It's true that we switched to building basehook.so and fullhook.so with CentOS. We did this because a dynamic dependency on the "musl" libraries that were easier to avoid when building under Centos. The goal is that these libraries work on most (all) Linux distros. Fullhook (the program, and test.sh that calls it were added mostly as development and build tools, so this may have slipped through. I will both document fullhook, the program, along with test.sh, and confirm that they work as intended. It would help me to know if a) Are the *hook.so libraries nevertheless working for you on Centos? and b) Which version of readhook are you using? I'll be starting with the stack-protector-all flag. Thanks for pointing it out! :-) -Roy

**Comment by rsundahl** [comment] 2018-03-07 00:20
I was able to reproduce this issue and confirmed that you are correct, we don't want stack-protector-all for the main program. I have made the change to the Dockerfile and will include it in the next release in the next few days. I will leave this issue open until the release is available. Thanks again. -Roy

**Comment by rsundahl** [comment] 2018-03-08 22:06
Fixed with release of readhook v1.2.1.

**Closed by rsundahl** 2018-03-08 22:06 UTC
